In [ ]:
#vae

In [1]:
!python main_ae_with_ufo_space_multi_domain.py --data_name ml_100k_action_fantasy --limits 0.5,0.5 --folder_save_model VAE_MULTI_DOMAIN --task_ids 0,1 --use_task_mask 1 --n_epochs 10 --lr 1e-3 --epoch_not_binary 9

     uid      sid
0      2  281 308
1      3      181
2      4      260
3      5  453 423
4      6   28 423
..   ...      ...
932  939  254 411
933  940      879
934  941      147
935  942  174 423
936  943   234 72

[937 rows x 2 columns]
get data success
start training
epoch 0 | test score task 0: recall@50: 0.6457
epoch 0 | test score all task: recall@50: 0.6457
epoch 1 | test score task 0: recall@50: 0.7263
epoch 1 | test score all task: recall@50: 0.7263
epoch 2 | test score task 0: recall@50: 0.7615
epoch 2 | test score all task: recall@50: 0.7615
epoch 3 | test score task 0: recall@50: 0.7866
epoch 3 | test score all task: recall@50: 0.7866
epoch 4 | test score task 0: recall@50: 0.7705
epoch 4 | test score all task: recall@50: 0.7705
epoch 5 | test score task 0: recall@50: 0.7882
epoch 5 | test score all task: recall@50: 0.7882
epoch 6 | test score task 0: recall@50: 0.8036
epoch 6 | test score all task: recall@50: 0.8036
epoch 7 | test score task 0: recall@50: 0.8052
epoch 7 |

<frozen importlib._bootstrap>:228: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject
C:\Users\admin\project\new_UFO_SPACE\main_ae_with_ufo_space_multi_domain.py:51: RuntimeWarning: invalid value encountered in true_divide
  return DCG / IDCG
C:\Users\admin\project\new_UFO_SPACE\main_ae_with_ufo_space_multi_domain.py:63: RuntimeWarning: invalid value encountered in true_divide
  recall = tmp / np.minimum(k, X_true_binary.sum(axis=1))
C:\Users\admin\project\new_UFO_SPACE\mask_optimization_for_vae.py:133: UserWarning: This overload of add_ is deprecated:
	add_(Number alpha, Tensor other)
Consider using one of the following signatures instead:
	add_(Tensor other, *, Number alpha) (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\python_arg_parser.cpp:1420.)
  next_m.mul_(beta1).add_(1 - beta1, grad)


In [2]:
!python main_ae_with_ufo_space_multi_domain.py --data_name ml_100k_action_fantasy --limits 0.6,0.6 --folder_save_model VAE_MULTI_DOMAIN --task_ids 1,0 --use_task_mask 0 --n_epochs 10 --lr 1e-3

     uid      sid
0      2  281 308
1      3      181
2      4      260
3      5  453 423
4      6   28 423
..   ...      ...
932  939  254 411
933  940      879
934  941      147
935  942  174 423
936  943   234 72

[937 rows x 2 columns]
get data success
start training
epoch 0 | test score task 1: recall@50: 0.8630
epoch 0 | test score all task: recall@50: 0.8630
epoch 1 | test score task 1: recall@50: 0.9609
epoch 1 | test score all task: recall@50: 0.9609
epoch 2 | test score task 1: recall@50: 1.0000
epoch 2 | test score all task: recall@50: 1.0000
epoch 3 | test score task 1: recall@50: 1.0000
epoch 3 | test score all task: recall@50: 1.0000
epoch 4 | test score task 1: recall@50: 1.0000
epoch 4 | test score all task: recall@50: 1.0000
epoch 5 | test score task 1: recall@50: 1.0000
epoch 5 | test score all task: recall@50: 1.0000
epoch 6 | test score task 1: recall@50: 1.0000
epoch 6 | test score all task: recall@50: 1.0000
epoch 7 | test score task 1: recall@50: 1.0000
epoch 7 |

<frozen importlib._bootstrap>:228: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject
C:\Users\admin\project\new_UFO_SPACE\main_ae_with_ufo_space_multi_domain.py:51: RuntimeWarning: invalid value encountered in true_divide
  return DCG / IDCG
C:\Users\admin\project\new_UFO_SPACE\main_ae_with_ufo_space_multi_domain.py:63: RuntimeWarning: invalid value encountered in true_divide
  recall = tmp / np.minimum(k, X_true_binary.sum(axis=1))


In [18]:
!python main_ae_with_ufo_space_multi_domain.py --data_name ml_100k_action_fantasy --limits 0.6,0.6 --folder_save_model VAE_MULTI_DOMAIN --task_ids 0,1 --use_task_mask 1 --n_epochs 10 --lr 1e-3 --use_task_mask_for_gradient_protecting 0  --epoch_not_binary 9

     uid      sid
0      2  281 308
1      3      181
2      4      260
3      5  453 423
4      6   28 423
..   ...      ...
932  939  254 411
933  940      879
934  941      147
935  942  174 423
936  943   234 72

[937 rows x 2 columns]
get data success
start training
epoch 0 | test score task 0: recall@50: 0.6457
epoch 0 | test score all task: recall@50: 0.6457
epoch 1 | test score task 0: recall@50: 0.7263
epoch 1 | test score all task: recall@50: 0.7263
epoch 2 | test score task 0: recall@50: 0.7615
epoch 2 | test score all task: recall@50: 0.7615
epoch 3 | test score task 0: recall@50: 0.7866
epoch 3 | test score all task: recall@50: 0.7866
epoch 4 | test score task 0: recall@50: 0.7705
epoch 4 | test score all task: recall@50: 0.7705
epoch 5 | test score task 0: recall@50: 0.7882
epoch 5 | test score all task: recall@50: 0.7882
epoch 6 | test score task 0: recall@50: 0.8036
epoch 6 | test score all task: recall@50: 0.8036
epoch 7 | test score task 0: recall@50: 0.8052
epoch 7 |

<frozen importlib._bootstrap>:228: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject
C:\Users\admin\project\new_UFO_SPACE\main_ae_with_ufo_space_multi_domain.py:51: RuntimeWarning: invalid value encountered in true_divide
  return DCG / IDCG
C:\Users\admin\project\new_UFO_SPACE\main_ae_with_ufo_space_multi_domain.py:63: RuntimeWarning: invalid value encountered in true_divide
  recall = tmp / np.minimum(k, X_true_binary.sum(axis=1))


In [4]:
#graph-based

In [1]:
!python main_graph_bi_interaction_with_ufo_space.py --data_name ml_100k --use_pretrain 0 --cf_print_every 16 --kg_print_every 16 --evaluate_every 1 --Ks '[20,50]' --cf_batch_size 1024  --lr 1e-3 --masking_train 1 --task_n_epochs "100,100" --task_ids "0,1" --limit 0.7 --limits 0.8,0.5 --use_two_loss_checkpoint 1 --folder_save_model GRAPH_BI_INTERACTION_WITH_UFO_SPACE_HARD_MASK_ONE_TASK_MASK_DRAMA_COMEDY --just_one_task_mask_for_users 1 --just_one_task_mask_for_items 1 --ensemble_learning 0 --epoch_not_binary_mask 3

All logs will be saved to trained_model/GRAPH_BI_INTERACTION_WITH_UFO_SPACE_HARD_MASK_ONE_TASK_MASK_DRAMA_COMEDY/ml_100k/embed-dim64_relation-dim64_random-walk_bi-interaction_64-32-16_lr0.001_pretrain0/log6.log
cuda
None
The maximum of the number of clusters for all entities is 255
[  1   1   1 ... 943 943 943]
[0]
[  1   2   2 ... 942 943 943]
[0]
[  1   1   1 ... 943 943 943]
Max num interactions is 1
User features is not existed
Item features is not existed
1
2
3
2627
4
[943, 1682]
1684
[74]
---------------------------------SEP----------------------------------------------
loz
5.302227e-05
loz
0.0010604454
loz
0.0002453639588120458
loz
0.00016967126
loz
0.0074231178
loz
0.0014783578742394192
loz
0.0029162248
loz
0.05461294
loz
0.018857079108342605
loz
0.0039236476
loz
0.18345705
loz
0.04419830253028111
loz
0.0039236476
loz
0.07211029
loz
0.024364287847005544
loz
0.00407211
loz
0.18133616
loz
0.04655928191131535
loz
0.005090138
loz
0.09172852
loz
0.03258669564282016
loz
0.0046235416


<frozen importlib._bootstrap>:228: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject
2023-06-16 21:51:05,594 - root - INFO - Namespace(seed=2019, data_name='ml_100k', data_dir='datasets/', use_pretrain=0, pretrain_embedding_dir='datasets/pretrain/', pretrain_model_path='trained_model/model.pth', cf_batch_size=1024, kg_batch_size=2048, test_batch_size=10000, embed_dim=64, relation_dim=64, laplacian_type='random-walk', aggregation_type='bi-interaction', conv_dim_list='[64, 32, 16]', mess_dropout='[0.1, 0.1, 0.1]', kg_l2loss_lambda=1e-05, cf_l2loss_lambda=1e-05, lr=0.001, n_epoch=1000, stopping_steps=30, cf_print_every=16, kg_print_every=16, evaluate_every=1, Ks="'[20,50]'", hard_negative_sampling=0, one_or_two=1, dropout_net=1, data_centric=0, train_kg=1, train_cf=1, masking_train=1, n_clusters=1000, n_samples=10, full_sampling=0, n_interactions=0, downstream_task_id=1, pretrain_task_i

In [2]:
!python main_graph_bi_interaction_with_ufo_space.py --data_name ml_100k --use_pretrain 0 --cf_print_every 16 --kg_print_every 16 --evaluate_every 1 --Ks '[20,50]' --cf_batch_size 1024  --lr 1e-3 --masking_train 1 --task_n_epochs "100,100" --task_ids "0,1" --limit 0.7 --limits 0.7,0.7 --use_two_loss_checkpoint 1 --folder_save_model GRAPH_BI_INTERACTION_WITH_UFO_SPACE_SOFT_MASK_ONE_TASK_MASK_DRAMA_COMEDY --just_one_task_mask_for_users 1 --just_one_task_mask_for_items 1 --ensemble_learning 0 --epoch_not_binary_mask 1000

All logs will be saved to trained_model/GRAPH_BI_INTERACTION_WITH_UFO_SPACE_SOFT_MASK_ONE_TASK_MASK_DRAMA_COMEDY/ml_100k/embed-dim64_relation-dim64_random-walk_bi-interaction_64-32-16_lr0.001_pretrain0/log0.log
cuda
None
The maximum of the number of clusters for all entities is 255
[  1   1   1 ... 943 943 943]
[0]
[  1   2   2 ... 942 943 943]
[0]
[  1   1   1 ... 943 943 943]
Max num interactions is 1
User features is not existed
Item features is not existed
1
2
3
2627
4
[943, 1682]
1684
[74]
---------------------------------SEP----------------------------------------------
loz
5.302227e-05
loz
0.0010604454
loz
0.0002453639588120458
loz
0.00016967126
loz
0.0074231178
loz
0.0014783578742394192
loz
0.0029162248
loz
0.05461294
loz
0.018857079108342605
loz
0.0039236476
loz
0.18345705
loz
0.04419830253028111
loz
0.00397667
loz
0.07264051
loz
0.02449701371417734
loz
0.00407211
loz
0.18133616
loz
0.046533715353951864
loz
0.00514316
loz
0.09278897
loz
0.03259492857527516
loz
0.0046023326
loz

<frozen importlib._bootstrap>:228: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject
2023-06-12 02:55:15,275 - root - INFO - Namespace(seed=2019, data_name='ml_100k', data_dir='datasets/', use_pretrain=0, pretrain_embedding_dir='datasets/pretrain/', pretrain_model_path='trained_model/model.pth', cf_batch_size=1024, kg_batch_size=2048, test_batch_size=10000, embed_dim=64, relation_dim=64, laplacian_type='random-walk', aggregation_type='bi-interaction', conv_dim_list='[64, 32, 16]', mess_dropout='[0.1, 0.1, 0.1]', kg_l2loss_lambda=1e-05, cf_l2loss_lambda=1e-05, lr=0.001, n_epoch=1000, stopping_steps=30, cf_print_every=16, kg_print_every=16, evaluate_every=1, Ks="'[20,50]'", hard_negative_sampling=0, one_or_two=1, dropout_net=1, data_centric=0, train_kg=1, train_cf=1, masking_train=1, n_clusters=1000, n_samples=10, full_sampling=0, n_interactions=0, downstream_task_id=1, pretrain_task_i

In [3]:
!python main_graph_bi_interaction_with_ufo_space.py --data_name ml_100k --use_pretrain 0 --cf_print_every 16 --kg_print_every 16 --evaluate_every 1 --Ks '[20,50]' --cf_batch_size 1024  --lr 1e-3 --masking_train 1 --task_n_epochs "100,100" --task_ids "0,1" --limit 0.7 --limits 0.7,0.7 --use_two_loss_checkpoint 1 --folder_save_model GRAPH_BI_INTERACTION_WITH_UFO_SPACE_SOFT_MASK_NO_MASK_DRAMA_COMEDY --epoch_not_binary_mask 3 --use_task_mask 0 --just_one_task_mask_for_users 1 --just_one_task_mask_for_items 1 --ensemble_learning 0

All logs will be saved to trained_model/GRAPH_BI_INTERACTION_WITH_UFO_SPACE_SOFT_MASK_NO_MASK_DRAMA_COMEDY/ml_100k/embed-dim64_relation-dim64_random-walk_bi-interaction_64-32-16_lr0.001_pretrain0/log0.log
cuda
None
The maximum of the number of clusters for all entities is 255
[  1   1   1 ... 943 943 943]
[0]
[  1   2   2 ... 942 943 943]
[0]
[  1   1   1 ... 943 943 943]
Max num interactions is 1
User features is not existed
Item features is not existed
1
2
3
2627
4
[943, 1682]
1684
[74]
---------------------------------SEP----------------------------------------------
loz
0.002386002
loz
0.04559915
loz
0.013616429756541554
loz
0.003626723
loz
0.16861081
loz
0.038090192272897075
loz
0.0051961825
loz
0.09597031
loz
0.0321048723138085
loz
0.005090137
loz
0.23276776
loz
0.05983901035454238
loz
0.0065747616
loz
0.117709436
loz
0.043464256343316736
loz
0.005535525
loz
0.25344646
loz
0.07035525737411076
loz
0.0072640507
loz
0.12937434
loz
0.049015020481843204
loz
0.0055779424
loz
0.25079533

<frozen importlib._bootstrap>:228: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject
2023-06-12 03:29:02,188 - root - INFO - Namespace(seed=2019, data_name='ml_100k', data_dir='datasets/', use_pretrain=0, pretrain_embedding_dir='datasets/pretrain/', pretrain_model_path='trained_model/model.pth', cf_batch_size=1024, kg_batch_size=2048, test_batch_size=10000, embed_dim=64, relation_dim=64, laplacian_type='random-walk', aggregation_type='bi-interaction', conv_dim_list='[64, 32, 16]', mess_dropout='[0.1, 0.1, 0.1]', kg_l2loss_lambda=1e-05, cf_l2loss_lambda=1e-05, lr=0.001, n_epoch=1000, stopping_steps=30, cf_print_every=16, kg_print_every=16, evaluate_every=1, Ks="'[20,50]'", hard_negative_sampling=0, one_or_two=1, dropout_net=1, data_centric=0, train_kg=1, train_cf=1, masking_train=1, n_clusters=1000, n_samples=10, full_sampling=0, n_interactions=0, downstream_task_id=1, pretrain_task_i

In [2]:
!python main_graph_bi_interaction_with_ufo_space.py --data_name ml_100k --use_pretrain 0 --cf_print_every 16 --kg_print_every 16 --evaluate_every 1 --Ks '[20,50]' --cf_batch_size 1024  --lr 1e-3 --masking_train 1 --task_n_epochs "100,100" --task_ids "0,1" --limit 0.7 --limits 0.8,0.5 --use_two_loss_checkpoint 1 --folder_save_model GRAPH_BI_INTERACTION_WITH_UFO_SPACE_NO_TASK_MASK_FOR_GRADIENT_PROTECTING_NEW_DRAMvA_COMEDY --epoch_not_binary_mask 3 --just_one_task_mask_for_users 1 --just_one_task_mask_for_items 1 --ensemble_learning 0 --use_task_mask_for_gradient_protecting 0

All logs will be saved to trained_model/GRAPH_BI_INTERACTION_WITH_UFO_SPACE_NO_TASK_MASK_FOR_GRADIENT_PROTECTING_NEW_DRAMvA_COMEDY/ml_100k/embed-dim64_relation-dim64_random-walk_bi-interaction_64-32-16_lr0.001_pretrain0/log2.log
cuda
None
The maximum of the number of clusters for all entities is 255
[  1   1   1 ... 943 943 943]
[0]
[  1   2   2 ... 942 943 943]
[0]
[  1   1   1 ... 943 943 943]
Max num interactions is 1
User features is not existed
Item features is not existed
1
2
3
2627
4
[943, 1682]
1684
[74]
---------------------------------SEP----------------------------------------------
loz
5.302227e-05
loz
0.0010604454
loz
0.0002453639588120458
loz
0.00016967126
loz
0.0074231178
loz
0.0014783578742394192
loz
0.0029162248
loz
0.05461294
loz
0.018857079108342605
loz
0.0039236476
loz
0.18345705
loz
0.04419830253028111
loz
0.0039236476
loz
0.07211029
loz
0.024364287847005544
loz
0.00407211
loz
0.18133616
loz
0.04656171597301275
loz
0.005090138
loz
0.09172852
loz
0.03245384372220796

<frozen importlib._bootstrap>:228: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject
2023-06-12 08:34:38,357 - root - INFO - Namespace(seed=2019, data_name='ml_100k', data_dir='datasets/', use_pretrain=0, pretrain_embedding_dir='datasets/pretrain/', pretrain_model_path='trained_model/model.pth', cf_batch_size=1024, kg_batch_size=2048, test_batch_size=10000, embed_dim=64, relation_dim=64, laplacian_type='random-walk', aggregation_type='bi-interaction', conv_dim_list='[64, 32, 16]', mess_dropout='[0.1, 0.1, 0.1]', kg_l2loss_lambda=1e-05, cf_l2loss_lambda=1e-05, lr=0.001, n_epoch=1000, stopping_steps=30, cf_print_every=16, kg_print_every=16, evaluate_every=1, Ks="'[20,50]'", hard_negative_sampling=0, one_or_two=1, dropout_net=1, data_centric=0, train_kg=1, train_cf=1, masking_train=1, n_clusters=1000, n_samples=10, full_sampling=0, n_interactions=0, downstream_task_id=1, pretrain_task_i

In [5]:
#mf

In [2]:
!python main_graph_bi_interaction_with_ufo_space.py --data_name ml_100k --use_pretrain 0 --cf_print_every 16 --kg_print_every 16 --evaluate_every 1 --Ks '[20,50]' --cf_batch_size 1024  --lr 1e-3 --masking_train 1 --task_n_epochs "100,100" --task_ids "0,1" --limit 0.7 --limits 0.8,0.5 --use_two_loss_checkpoint 1 --folder_save_model GRAPH_BI_INTERACTION_WITH_UFO_SPACE_HARD_MASK_ONE_TASK_MASK_DRAMA_COMEDY_MF --just_one_task_mask_for_users 1 --just_one_task_mask_for_items 1 --ensemble_learning 0 --epoch_not_binary_mask 3 --mf 1

All logs will be saved to trained_model/GRAPH_BI_INTERACTION_WITH_UFO_SPACE_HARD_MASK_ONE_TASK_MASK_DRAMA_COMEDY_MF/ml_100k/embed-dim64_relation-dim64_random-walk_bi-interaction_64-32-16_lr0.001_pretrain0/log3.log
cuda
None
The maximum of the number of clusters for all entities is 255
[  1   1   1 ... 943 943 943]
[0]
[  1   2   2 ... 942 943 943]
[0]
[  1   1   1 ... 943 943 943]
Max num interactions is 1
User features is not existed
Item features is not existed
1
2
3
2627
4
[943, 1682]
1684
[74]
---------------------------------SEP----------------------------------------------
loz
0.0069459174
loz
0.12672323
loz
0.05286708501363179
loz
0.004665959
loz
0.21420997
loz
0.07056841236272149
loz
0.015588548
loz
0.28844115
loz
0.10984550259351218
loz
0.009862142
loz
0.45493108
loz
0.14336001532858894
loz
0.015111348
loz
0.27730647
loz
0.1116615763837903
loz
0.010116648
loz
0.46447507
loz
0.14933133917958066
loz
0.015270414
loz
0.2804878
loz
0.11182114525126666
loz
0.010010604
loz
0.4602333


<frozen importlib._bootstrap>:228: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject
2023-06-16 22:23:22,729 - root - INFO - Namespace(seed=2019, data_name='ml_100k', data_dir='datasets/', use_pretrain=0, pretrain_embedding_dir='datasets/pretrain/', pretrain_model_path='trained_model/model.pth', cf_batch_size=1024, kg_batch_size=2048, test_batch_size=10000, embed_dim=64, relation_dim=64, laplacian_type='random-walk', aggregation_type='bi-interaction', conv_dim_list='[64, 32, 16]', mess_dropout='[0.1, 0.1, 0.1]', kg_l2loss_lambda=1e-05, cf_l2loss_lambda=1e-05, lr=0.001, n_epoch=1000, stopping_steps=30, cf_print_every=16, kg_print_every=16, evaluate_every=1, Ks="'[20,50]'", hard_negative_sampling=0, one_or_two=1, dropout_net=1, data_centric=0, train_kg=1, train_cf=1, masking_train=1, n_clusters=1000, n_samples=10, full_sampling=0, n_interactions=0, downstream_task_id=1, pretrain_task_i

In [5]:
!python main_graph_bi_interaction_with_ufo_space.py --data_name ml_100k --use_pretrain 0 --cf_print_every 16 --kg_print_every 16 --evaluate_every 1 --Ks '[20,50]' --cf_batch_size 1024  --lr 1e-3 --masking_train 1 --task_n_epochs "100,100" --task_ids "0,1" --limit 0.7 --limits 0.7,0.5 --use_two_loss_checkpoint 1 --folder_save_model UFO_SPACE_8_SOFT_MASK_ONE_TASK_MASK_DRAMA_COMEDY_MF --just_one_task_mask_for_users 1 --just_one_task_mask_for_items 1 --ensemble_learning 0 --epoch_not_binary_mask 1000 --mf 1

All logs will be saved to trained_model/UFO_SPACE_8_SOFT_MASK_ONE_TASK_MASK_DRAMA_COMEDY_MF/ml_100k/embed-dim64_relation-dim64_random-walk_bi-interaction_64-32-16_lr0.001_pretrain0/log7.log
cuda
None
The maximum of the number of clusters for all entities is 255
[  1   1   1 ... 943 943 943]
[0]
[  1   2   2 ... 942 943 943]
[0]
[  1   1   1 ... 943 943 943]
Max num interactions is 1
User features is not existed
Item features is not existed
1
2
3
2627
4
[943, 1682]
1684
[74]
---------------------------------SEP----------------------------------------------
loz
0.0069459174
loz
0.12672323
loz
0.05286708501363179
loz
0.004665959
loz
0.21420997
loz
0.07056841236272149
loz
0.015588548
loz
0.28844115
loz
0.10984550259351218
loz
0.009862142
loz
0.45493108
loz
0.14336001532858894
loz
0.015111348
loz
0.27730647
loz
0.1116615763837903
loz
0.010116648
loz
0.46447507
loz
0.14933133917958066
loz
0.015270414
loz
0.2804878
loz
0.11182114525126666
loz
0.010010604
loz
0.4602333
loz
0.1479535115649086
l

<frozen importlib._bootstrap>:228: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject
2023-06-12 04:36:44,245 - root - INFO - Namespace(seed=2019, data_name='ml_100k', data_dir='datasets/', use_pretrain=0, pretrain_embedding_dir='datasets/pretrain/', pretrain_model_path='trained_model/model.pth', cf_batch_size=1024, kg_batch_size=2048, test_batch_size=10000, embed_dim=64, relation_dim=64, laplacian_type='random-walk', aggregation_type='bi-interaction', conv_dim_list='[64, 32, 16]', mess_dropout='[0.1, 0.1, 0.1]', kg_l2loss_lambda=1e-05, cf_l2loss_lambda=1e-05, lr=0.001, n_epoch=1000, stopping_steps=30, cf_print_every=16, kg_print_every=16, evaluate_every=1, Ks="'[20,50]'", hard_negative_sampling=0, one_or_two=1, dropout_net=1, data_centric=0, train_kg=1, train_cf=1, masking_train=1, n_clusters=1000, n_samples=10, full_sampling=0, n_interactions=0, downstream_task_id=1, pretrain_task_i

In [6]:
!python main_graph_bi_interaction_with_ufo_space.py --data_name ml_100k --use_pretrain 0 --cf_print_every 16 --kg_print_every 16 --evaluate_every 1 --Ks '[20,50]' --cf_batch_size 1024  --lr 1e-3 --masking_train 1 --task_n_epochs "100,100" --task_ids "0,1" --limit 0.7 --limits 0.7,0.7 --use_two_loss_checkpoint 1 --folder_save_model GRAPH_BI_INTERACTIONS_WITH_UFO_SPACE_NO_TASK_MASK_DRAMA_COMEDY_MF --epoch_not_binary_mask 3 --use_task_mask 0 --mf 1 --just_one_task_mask_for_users 1 --just_one_task_mask_for_items 1 --ensemble_learning 0

All logs will be saved to trained_model/GRAPH_BI_INTERACTIONS_WITH_UFO_SPACE_NO_TASK_MASK_DRAMA_COMEDY_MF/ml_100k/embed-dim64_relation-dim64_random-walk_bi-interaction_64-32-16_lr0.001_pretrain0/log0.log
cuda
None
The maximum of the number of clusters for all entities is 255
[  1   1   1 ... 943 943 943]
[0]
[  1   2   2 ... 942 943 943]
[0]
[  1   1   1 ... 943 943 943]
Max num interactions is 1
User features is not existed
Item features is not existed
1
2
3
2627
4
[943, 1682]
1684
[74]
---------------------------------SEP----------------------------------------------
loz
0.0069459174
loz
0.12672323
loz
0.05194444711981667
loz
0.0045811236
loz
0.21049841
loz
0.06868495479301072
loz
0.015429481
loz
0.28579003
loz
0.11094074873618841
loz
0.009819724
loz
0.45281017
loz
0.1448237666227179
loz
0.015323437
loz
0.2826087
loz
0.11285492285775128
loz
0.010095439
loz
0.46553552
loz
0.14970653239248521
loz
0.015800636
loz
0.2916225
loz
0.11592973646170518
loz
0.010222692
loz
0.47030753
loz
0.151

<frozen importlib._bootstrap>:228: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject
2023-06-12 05:06:57,003 - root - INFO - Namespace(seed=2019, data_name='ml_100k', data_dir='datasets/', use_pretrain=0, pretrain_embedding_dir='datasets/pretrain/', pretrain_model_path='trained_model/model.pth', cf_batch_size=1024, kg_batch_size=2048, test_batch_size=10000, embed_dim=64, relation_dim=64, laplacian_type='random-walk', aggregation_type='bi-interaction', conv_dim_list='[64, 32, 16]', mess_dropout='[0.1, 0.1, 0.1]', kg_l2loss_lambda=1e-05, cf_l2loss_lambda=1e-05, lr=0.001, n_epoch=1000, stopping_steps=30, cf_print_every=16, kg_print_every=16, evaluate_every=1, Ks="'[20,50]'", hard_negative_sampling=0, one_or_two=1, dropout_net=1, data_centric=0, train_kg=1, train_cf=1, masking_train=1, n_clusters=1000, n_samples=10, full_sampling=0, n_interactions=0, downstream_task_id=1, pretrain_task_i

In [7]:
!python main_graph_bi_interaction_with_ufo_space.py --data_name ml_100k --use_pretrain 0 --cf_print_every 16 --kg_print_every 16 --evaluate_every 1 --Ks '[20,50]' --cf_batch_size 1024  --lr 1e-3 --masking_train 1 --task_n_epochs "100,100" --task_ids "0,1" --limit 0.7 --limits 0.8,0.5 --use_two_loss_checkpoint 1 --folder_save_model GRAPH_BI_INTERACTIONS_WITH_UFO_SPACE_NO_TASK_MASK_FOR_GRADIENT_PROTECTING_NEW_DRAMA_COMEDY_MF --epoch_not_binary_mask 3 --use_task_mask_for_gradient_protecting 0 --mf 1 --just_one_task_mask_for_users 1 --just_one_task_mask_for_items 1 --ensemble_learning 0

All logs will be saved to trained_model/GRAPH_BI_INTERACTIONS_WITH_UFO_SPACE_NO_TASK_MASK_FOR_GRADIENT_PROTECTING_NEW_DRAMA_COMEDY_MF/ml_100k/embed-dim64_relation-dim64_random-walk_bi-interaction_64-32-16_lr0.001_pretrain0/log0.log
cuda
None
The maximum of the number of clusters for all entities is 255
[  1   1   1 ... 943 943 943]
[0]
[  1   2   2 ... 942 943 943]
[0]
[  1   1   1 ... 943 943 943]
Max num interactions is 1
User features is not existed
Item features is not existed
1
2
3
2627
4
[943, 1682]
1684
[74]
---------------------------------SEP----------------------------------------------
loz
0.0069459174
loz
0.12672323
loz
0.05286708501363179
loz
0.004665959
loz
0.21420997
loz
0.07056841236272149
loz
0.015588548
loz
0.28844115
loz
0.10984550259351218
loz
0.009862142
loz
0.45493108
loz
0.14336001532858894
loz
0.015111348
loz
0.27730647
loz
0.1116615763837903
loz
0.010116648
loz
0.46447507
loz
0.14933133917958066
loz
0.015270414
loz
0.2804878
loz
0.11182114525126666
loz
0.010010

<frozen importlib._bootstrap>:228: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject
2023-06-12 05:36:39,990 - root - INFO - Namespace(seed=2019, data_name='ml_100k', data_dir='datasets/', use_pretrain=0, pretrain_embedding_dir='datasets/pretrain/', pretrain_model_path='trained_model/model.pth', cf_batch_size=1024, kg_batch_size=2048, test_batch_size=10000, embed_dim=64, relation_dim=64, laplacian_type='random-walk', aggregation_type='bi-interaction', conv_dim_list='[64, 32, 16]', mess_dropout='[0.1, 0.1, 0.1]', kg_l2loss_lambda=1e-05, cf_l2loss_lambda=1e-05, lr=0.001, n_epoch=1000, stopping_steps=30, cf_print_every=16, kg_print_every=16, evaluate_every=1, Ks="'[20,50]'", hard_negative_sampling=0, one_or_two=1, dropout_net=1, data_centric=0, train_kg=1, train_cf=1, masking_train=1, n_clusters=1000, n_samples=10, full_sampling=0, n_interactions=0, downstream_task_id=1, pretrain_task_i

In [ ]:
#compare to other baselines

In [ ]:
#graph_bi_interactions

In [3]:
!python main_graph_bi_interaction_multi_domain.py --data_name ml_100k --use_pretrain 0 --cf_print_every 16 --kg_print_every 16 --evaluate_every 1 --Ks '[20,50]' --cf_batch_size 1024  --lr 1e-3 --masking_train 1 --task_ids "0,1" --task_n_epochs "100,100" --n_epoch 200 --folder_save_model GRAPH_BI_INTERACTION_RAW_FOR_MULTI_DOMAIN 

All logs will be saved to trained_model/GRAPH_BI_INTERACTION_RAW_FOR_MULTI_DOMAIN/ml_100k/embed-dim64_relation-dim64_random-walk_bi-interaction_64-32-16_lr0.001_pretrain0/log3.log
cuda
None
The maximum of the number of clusters for all entities is 255
[  1   1   1 ... 943 943 943]
[0]
[  1   2   2 ... 942 943 943]
[0]
[  1   1   1 ... 943 943 943]
Max num interactions is 1
User features is not existed
Item features is not existed
1
2
3
2627
4
[  1   1   1 ... 943 943 943]
[0]
[  1   2   2 ... 942 943 943]
[0]
[  1   1   1 ... 943 943 943]
[943, 1682]
1684
[74]
---------------------------------SEP----------------------------------------------
[  1   1   1 ... 943 943 943]
[0]
[  1   2   2 ... 942 943 943]
[0]
[  1   1   1 ... 943 943 943]
Task id 0
No cold start
---------------------------------SEP----------------------------------------------
Task id 1
No cold start
---------------------------------SEP----------------------------------------------
[  1   1   1 ... 943 943 943]
[0]
[  1

<frozen importlib._bootstrap>:228: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject
2023-06-16 22:51:32,933 - root - INFO - Namespace(seed=2019, data_name='ml_100k', data_dir='datasets/', use_pretrain=0, pretrain_embedding_dir='datasets/pretrain/', pretrain_model_path='trained_model/model.pth', cf_batch_size=1024, kg_batch_size=2048, test_batch_size=10000, embed_dim=64, relation_dim=64, laplacian_type='random-walk', aggregation_type='bi-interaction', conv_dim_list='[64, 32, 16]', mess_dropout='[0.1, 0.1, 0.1]', kg_l2loss_lambda=1e-05, cf_l2loss_lambda=1e-05, lr=0.001, n_epoch=200, stopping_steps=30, cf_print_every=16, kg_print_every=16, evaluate_every=1, Ks="'[20,50]'", hard_negative_sampling=0, one_or_two=1, dropout_net=1, data_centric=0, train_kg=1, train_cf=1, masking_train=1, n_clusters=1000, n_samples=10, full_sampling=0, n_interactions=0, downstream_task_id=1, pretrain_task_id

In [4]:
#mf

In [5]:
!python main_graph_bi_interaction_multi_domain.py --data_name ml_100k --use_pretrain 0 --cf_print_every 16 --kg_print_every 16 --evaluate_every 1 --Ks '[20,50]' --cf_batch_size 1024  --lr 1e-3 --masking_train 1 --task_ids "0,1" --task_n_epochs "100,100" --n_epoch 200 --folder_save_model MATRIX_FACTORIZATION_RAW_FOR_MULTI_DOMAIN --mf 1 

All logs will be saved to trained_model/MATRIX_FACTORIZATION_RAW_FOR_MULTI_DOMAIN/ml_100k/embed-dim64_relation-dim64_random-walk_bi-interaction_64-32-16_lr0.001_pretrain0/log1.log
cuda
None
The maximum of the number of clusters for all entities is 255
[  1   1   1 ... 943 943 943]
[0]
[  1   2   2 ... 942 943 943]
[0]
[  1   1   1 ... 943 943 943]
Max num interactions is 1
User features is not existed
Item features is not existed
1
2
3
2627
4
[  1   1   1 ... 943 943 943]
[0]
[  1   2   2 ... 942 943 943]
[0]
[  1   1   1 ... 943 943 943]
[943, 1682]
1684
[74]
---------------------------------SEP----------------------------------------------
[  1   1   1 ... 943 943 943]
[0]
[  1   2   2 ... 942 943 943]
[0]
[  1   1   1 ... 943 943 943]
Task id 0
No cold start
---------------------------------SEP----------------------------------------------
Task id 1
No cold start
---------------------------------SEP----------------------------------------------
[  1   1   1 ... 943 943 943]
[0]
[  1

<frozen importlib._bootstrap>:228: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject
2023-06-16 23:27:04,380 - root - INFO - Namespace(seed=2019, data_name='ml_100k', data_dir='datasets/', use_pretrain=0, pretrain_embedding_dir='datasets/pretrain/', pretrain_model_path='trained_model/model.pth', cf_batch_size=1024, kg_batch_size=2048, test_batch_size=10000, embed_dim=64, relation_dim=64, laplacian_type='random-walk', aggregation_type='bi-interaction', conv_dim_list='[64, 32, 16]', mess_dropout='[0.1, 0.1, 0.1]', kg_l2loss_lambda=1e-05, cf_l2loss_lambda=1e-05, lr=0.001, n_epoch=200, stopping_steps=30, cf_print_every=16, kg_print_every=16, evaluate_every=1, Ks="'[20,50]'", hard_negative_sampling=0, one_or_two=1, dropout_net=1, data_centric=0, train_kg=1, train_cf=1, masking_train=1, n_clusters=1000, n_samples=10, full_sampling=0, n_interactions=0, downstream_task_id=1, pretrain_task_id

In [ ]:
#vae

In [3]:
!python main_ae_raw_multi_domain.py --data_name ml_100k_action_fantasy --limits 0.6,0.6 --folder_save_model VAE_RAW_MULTI_DOMAIN --task_ids 0,1 --use_task_mask 1 --n_epochs 100 --lr 1e-3 --vae_using_ufo_space 0

     uid      sid
0      2  281 308
1      3      181
2      4      260
3      5  453 423
4      6   28 423
..   ...      ...
932  939  254 411
933  940      879
934  941      147
935  942  174 423
936  943   234 72

[937 rows x 2 columns]
get data success
start training
epoch 0 | test score task 0: recall@50: 0.2978
epoch 0 | test score task 1: recall@50: 0.3209
epoch 0 | test score all task: recall@50: 0.3093
epoch 1 | test score task 0: recall@50: 0.4723
epoch 1 | test score task 1: recall@50: 0.4139
epoch 1 | test score all task: recall@50: 0.4431
epoch 2 | test score task 0: recall@50: 0.5704
epoch 2 | test score task 1: recall@50: 0.4217
epoch 2 | test score all task: recall@50: 0.4961
epoch 3 | test score task 0: recall@50: 0.6377
epoch 3 | test score task 1: recall@50: 0.4198
epoch 3 | test score all task: recall@50: 0.5287
epoch 4 | test score task 0: recall@50: 0.6708
epoch 4 | test score task 1: recall@50: 0.4022
epoch 4 | test score all task: recall@50: 0.5365
epoch 5 | tes

<frozen importlib._bootstrap>:228: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject
C:\Users\admin\project\new_UFO_SPACE\main_ae_raw_multi_domain.py:51: RuntimeWarning: invalid value encountered in true_divide
  return DCG / IDCG
C:\Users\admin\project\new_UFO_SPACE\main_ae_raw_multi_domain.py:63: RuntimeWarning: invalid value encountered in true_divide
  recall = tmp / np.minimum(k, X_true_binary.sum(axis=1))
